### ISSUE TITLE
eligible for funding via thanks.dev

### ISSUE THREAD

**Issue by anehzat** [dnsl48/fraction#102]
Hi Serge, thanks for all your contributions to open source.
I just wanted to let you know that you're eligible to claim funding for your package from our sponsor [Sentry](https://thanks.dev/d/gh/getsentry/dependencies). Let me know if this is something you'd like to claim via [thanks.dev](https://thanks.dev/home).

**Comment by dnsl48** [comment]
Hey @anehzat, thanks for reaching out.
I've already got some donations from Sentry via the GitHub sponsorship.
I'll check out the thanks.dev website too :+1:
