### ISSUE TITLE
Benchmark of parsing f64 and Decimal from string?

### ISSUE THREAD

**Issue by serzhiio** [dnsl48/fraction#11]
Hi! Did you compare perfomance of std::f64 and your Decimal from string conversions?

**Comment by dnsl48** [comment]
Hi. I don't think we will ever compete with `std::f64` or `std::f32` in performance. One of the goals of this library is to be lossless. In sake of not losing data it would usually be slower than native, close to CPU implementations. It also uses more memory as well.

Nonetheless, I don't think the performance is too bad. We try to keep it up, do as few allocations as possible etc. For most of the use cases this should be more than enough.
Either way, if you see some ways to improve, PRs or recommendations are welcome.
