### ISSUE TITLE
Add a simplify function to fraction type

### ISSUE THREAD

**Issue by pirsonxyz** [dnsl48/fraction#113]
This is useful when dealing with big fractions that can be simplified

**Comment by dnsl48** [comment]
Hi @pirsonxyz, all fractions are simplified by default in the constructor, unless you are using `GenericFraction::new_raw` method, which primary discrepancy is the lack of simplification for performance reasons.
Thus, you could use the `GenericFraction::new` constructor as the way to _simplify_ a fraction.
