### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by hbina** [dnsl48/fraction#19]
In https://docs.rs/fraction/0.6.2/fraction/prelude/index.html, the links to 

1. [Generic Fractions](https://docs.rs/fraction/0.6.2/fraction/enum.GenericFraction.html)
2. [Generic Decimal](https://docs.rs/fraction/0.6.2/fraction/prelude/struct.GenericDecimal.html)
3. [Dynamic Int](https://docs.rs/fraction/0.6.2/fraction/dynaint/enum.DynaInt.html)

are all broken.

**Comment by dnsl48** [comment]
Yes, they used to work in locally built documentation, doesn't seem to be the case for docs.rs though.
I guess we should check them again when releasing the next version.

**Comment by dnsl48** [comment]
`docs.rs` upgraded the toolchain, so all the links work fine in `0.6.3` version docs https://docs.rs/fraction/0.6.3/fraction/prelude/index.html
