### ISSUE TITLE
Why not implement num_traits::Real instead?

### ISSUE THREAD

**Issue by hbina** [dnsl48/fraction#24]
Instead of implementing this https://github.com/dnsl48/fraction/blob/c069bda24fd4e750778830d76c05306f6c725fb7/src/generic.rs#L21 why not use num_trait[1]?

What's your thought on this? Is there a problem with num_trait's trait that is incompatible with this crate?

[1]https://docs.rs/num-traits/0.2.12/num_traits/real/trait.Real.html

**Comment by dnsl48** [comment]
The main purpose of `GenericInteger` is to combine the necessary minimum of core traits required to work gracefully with both stack and heap allocated values and references.
`num_traits::Real` does not implement all necessary traits and provides some redundant ones. An even bigger problem with it its `Copy` implementation, which won't let us work with `BigInt`.

**Comment by hbina** [comment]
Also, are you considering formatting the codebase? :(

**Comment by dnsl48** [comment]
Yeah, most of it has been written before rustfmt got stablilized.
PRs are welcome :)
