### ISSUE TITLE
Why is zero() not equal to neg_zero()?

### ISSUE THREAD

**Issue by m-cat** [dnsl48/fraction#3]
Pretty simple to reproduce: `assert_eq!(BigFraction::zero(), BigFraction::neg_zero());`

Well, this is kind of annoying. One of the advantages of Fractions over floating point is that you can do exact comparisons. But now we have an edge case that we have to handle before each comparison. I don't see any reason for this being desired behavior.

**Comment by dnsl48** [comment]
Hi m-cat, thank you for reporting the issue! That was clearly a bug. Furthermore, not with just zeros, but with all negatives in general. I added some more tests around comparisons.
New version `0.3.7` with all the fixes has been released.

Cheers
