### ISSUE TITLE
Fraction::from_str can fail with overflow if fractional part ends with too many zeroes

### ISSUE THREAD

**Issue by khigia** [dnsl48/fraction#62]
`Fraction::from_str("10000000000000.0000000000").unwrap()` will fail with overflow error while it can be represented without loss.

The from_str implementation use the number of digits to guard against overflow, but in this case, the fractional part trailing 0 should not be counted.

This issue arise easily when using `bigdecimal::BigDecimal::to_string` as input of `Fraction::from_str` (conversion between bigdecimal and fraction may looks strange, but bigdecimal is better supported by postgresql while some code use Fraction for computation).

**Comment by dnsl48** [comment]
Yes, agree, that optimisation would be reasonable. Thank you for the PR!

**Comment by dnsl48** [comment]
Merged and released in `0.11.1`,
Thank you for the contribution @khigia!

**Comment by khigia** [comment]
Thanks for reviewing, merging and releasing so quickly!
