### ISSUE TITLE
Serialization support for DynaInt

### ISSUE THREAD

**Issue by optevo** [dnsl48/fraction#65]
Even though I have feature "with-serde-support" on, when I implement a struct or enum that contains DynaInt or any type that uses it and place #[derive(Serialize)] on my type I get:

error: the trait bound `DynaInt<u64, BigUint>: Serialize` is not satisfied
label: the trait `Serialize` is not implemented for `DynaInt<u64, BigUint>`

Serialization seems to work fine for GenericDecimal. I'm fairly new to Rust - is there something I'm doing wrong? Or is there some reason serialization is not supported for DynaInt?

**Comment by dnsl48** [comment]
I believe that was resolved in #66, thank you for the contribution! 
The patch is now released with `0.11.2`. I am closing this ticket, but if that doesn't solve your issue,
please feel free to reopen.
