### ISSUE TITLE
Fraction ceil and floor round negative fraction "the wrong way"

### ISSUE THREAD

**Issue by morri2** [dnsl48/fraction#81]
`Fraction::floor` rounds negative Fractions upwards (towards zero), and `Fraction::ceil` rounds negative fractions towards negative infinity. Since the docs says that `floor` should "Returns the largest integer less than or equal to the value" I'm assuming this is unintentional

```rs
let f = Fraction::new_neg(1u8, 2u8);
println!("{} {}", f.floor(), f.ceil());
```
This example prints `-0 -1` when the output should be `-1 -0`

**Comment by dnsl48** [comment]
The fix was released with 0.13.1.
Thanks again for the contribution!
